### ISSUE TITLE
Updated Project Description Document

### ISSUE THREAD

**Issue by sowthewind-reapthewhirlwind** [COS420-Fall23/Team-G#1]
Based on the comments from deliverable 0.

If the comments were not addressed, the document will be marked as 0.

If the comments are partially addressed, the document will be marked as 2.5.

You must document a changelog by replying to the Google document comments when you think an issue has been addressed. You must also reply to comments saying what you didn’t address.

Document: https://docs.google.com/document/d/1mdwVcvNii_XZXJZ_xzK_yhJkFj-v8JSG94TNJ9vnZHY/edit?usp=drive_link

**Comment by Quinn-Knowles** [comment]
can someone clarify if I needed to edit the linked document or the project description document?

**Comment by sowthewind-reapthewhirlwind** [comment]
Hi @Quinn-Knowles you need to edit the linked document sorry for the confusion
