### ISSUE TITLE
Updated User story document

### ISSUE THREAD

**Issue by sowthewind-reapthewhirlwind** [COS420-Fall23/Team-G#2]
Based on the comments from deliverable 0.

If the comments were not addressed, the document will be marked as 0.

If the comments are partially addressed, the document will be marked as 2.5.

You must document a changelog by replying to the Google document comments when you think an issue has been addressed. You must also reply to comments saying what you didn’t address.

document: https://docs.google.com/document/d/1B4nvO1UK4wHqGmwU7BIKR5suK_9lIxorPOPOaEFWVF8/edit?usp=drive_link

**Comment by knoxbrown** [comment]
Updated user story document. Replied to / resolved all comments from Dr. G
