### ISSUE TITLE
UI Mockups - 1

### ISSUE THREAD

**Issue by sowthewind-reapthewhirlwind** [COS420-Fall23/Team-G#21]

**Comment by JohnKearneyyy** [comment]
UI Mockup of the Ride Request page: https://miro.com/app/board/uXjVNcfnoXg=/
<img width="1018" alt="Screenshot 2023-10-22 at 9 05 11 PM" src="https://github.com/COS420-Fall23/Team-G/assets/143441853/32ee2cfc-9686-42d0-b1dd-107ec58b24db">
