### ISSUE TITLE
Compile Use Case Descriptions & Proof Read Them

### ISSUE THREAD

**Issue by Dymonkeys** [COS420-Fall23/Team-G#23]
Create a document to compile the use case descriptions that have been completed in  Assignment 2. Ensure that the document is in the shared folder. Make sure any additional use case descriptions are added to this document, and proofread them making sure they work together.

Requirements listed for Use Case Descriptions:

If the number of use case diagrams/models is less than 2, deduct -10 points.

Use case diagrams/models should be correct and have the correct links.

Use cases should start from the actor. If not, deduct -2 points for each mistake.

Use case descriptions should follow the templates/guidelines from slides or the given template.

If they do not match, deduct -5 points for each mistake.

The name of the UCD should match with the use cases in the diagram.

If they do not match, deduct -1 point per each mistake.

The related use cases should be shown correctly in the UCD

If they do not show correctly, deduct -1 point per each mistake.

For every other mistake, deduct -1 points for each.

**Comment by knoxbrown** [comment]
https://docs.google.com/document/d/1P9Eg7P_d63U0Y0630q8E75KJH543UUThz8P76rnW5ss/edit
