### ISSUE TITLE
Create 2 Use Case Diagrams

### ISSUE THREAD

**Issue by Dymonkeys** [COS420-Fall23/Team-G#24]
Create 2 use case diagrams, each with at least 3 use cases from the use case description issue. Post a link to the Miro page on this issue (or another tool used to create them). 

Use Case Diagram Requirements:

If the number of use case diagrams/models is less than 2, deduct -10 points.

Use case diagrams/models should be correct and have the correct links.

The name of the UCD should match with the use cases in the diagram.

If they do not match, deduct -1 point per each mistake.

The related use cases should be shown correctly in the UCD

If they do not show correctly, deduct -1 point per each mistake.

For every other mistake, deduct -1 points for each.

**Comment by KledisZ** [comment]
https://docs.google.com/document/d/1bJSOb0SJoJ6Z898xsiQIMFbPGHZDzxyZM90LSzS4rgI/edit
