### ISSUE TITLE
Sprint Backlog 1

### ISSUE THREAD

**Issue by sowthewind-reapthewhirlwind** [COS420-Fall23/Team-G#4]
Use (https://docs.google.com/spreadsheets/d/18AXZZxBCle6GE3ufvEgtNAKRVHvWBjZV/edit?usp=sharing&ouid=108788083057609121398&rtpof=true&sd=true)

Should reflect the product backlog. That is, all the user stories that are assigned to Sprint 1 in the product backlog, should be shown in the Sprint Backlog 1.

For any missing user story, deduct -2 points.

If the Sprint Backlog 1 does not reflect the product backlog, deduct -5 points.

You should have other technical tasks in your backlog

You should also have other tasks in the backlog, like documentation, requirements, UI mockups, etc. As covered in class sessions, these are called non-technical stories.

All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.

**Comment by KledisZ** [comment]
https://docs.google.com/spreadsheets/d/1qyo5sVjDJErHDhkcm6U-6JGMV_jN8WF2/edit#gid=1448491115
