### ISSUE TITLE
Address Deliverable 2 Feedback

### ISSUE THREAD

**Issue by Dymonkeys** [COS420-Fall23/Team-G#61]
When you have addressed the feedback to your own work, comment on your changes on this issue. Do not close the issue until we have confirmed that all feedback is addressed

**Comment by Dymonkeys** [comment]
Added Preconditions to my use case descriptions

**Comment by KledisZ** [comment]
Preconditions and related use cases fixed, along with extensions and inclusions in the use case descriptions

**Comment by greglnelson** [comment]
Need to add a task to check that all the D2 feedback e.g. on use cases has been addressed
