### ISSUE TITLE
Backlog item ID: 3 Home screen

### ISSUE THREAD

**Issue by Quinn-Knowles** [COS420-Fall23/Team-G#62]
Task from project backlog
ID: 3
user story: As a user, I would like to have a home screen when I log into the application so I can navigate to other parts of the app

**Comment by sowthewind-reapthewhirlwind** [comment]
![image](https://github.com/COS420-Fall23/Team-G/assets/39146583/7915e967-fba7-4b59-aca9-9ef09921e563)
