### ISSUE TITLE
UI Mockups

### ISSUE THREAD

**Issue by TiffanyTHa** [COS420-Fall23/Team-G#63]
- If there are no UI mockups, deduct -40 points. 

- You should have wireflows or a series of mockups or an interactive prototype in Adobe XD, Figma, or similar software, for the most valuable features in the application. The application should be complete.

- All screens need to be high fidelity wireframe/wireflows or made as an interactive prototype in Figma, Adobe XD, etc.

- Most important/valuable screens have concrete actual values in them instead of filler text

**Comment by TiffanyTHa** [comment]
https://miro.com/app/board/uXjVNcfnoXg=/

**Comment by JohnKearneyyy** [comment]
https://miro.com/app/board/uXjVNcfnoXg=/
