### ISSUE TITLE
Usability Testing Revisions

### ISSUE THREAD

**Issue by TiffanyTHa** [COS420-Fall23/Team-G#64]
- Write a usability testing script

- Do usability tests with at least 3 other people, and write up consolidated notes and planned revisions

- Revise the mockups based on usability testing results

**Comment by TiffanyTHa** [comment]
https://docs.google.com/document/d/1wVoriLdpuOkH0RJQz_eGS6duGiuLmp8HBPb7bnMgC9I/edit

**Comment by JohnKearneyyy** [comment]
https://docs.google.com/document/d/1wVoriLdpuOkH0RJQz_eGS6duGiuLmp8HBPb7bnMgC9I/edit
