### ISSUE TITLE
Address Deliverable 3 Feedback

### ISSUE THREAD

**Issue by Dymonkeys** [COS420-Fall23/Team-G#72]
When you have addressed the work, comment on your changes on this issue.

**Comment by KledisZ** [comment]
Assigned these tasks:
Tasks:
D3-1) [task] Decide on a quality checking process and implement it for D4. Write  it into your policies on Github and write it in your Discord channel and @ me in the message so I can give you feedback on it. This includes fixing: “Without assigning tasks for checking specific work to a specific person, it leads to that not getting done. You can do this by either @’ing people on a comment on the item like “@Name quality check this and compare to example docs”. Or have another field on each task called “reviewer” and assign reviewers when tasks are first created”

D3-2) [task] You need quality checking tasks at the granularity of “check use case 5 and 10”. Tasks like “Address feedback” on <giant document> aren’t empirically working well enough. Also, the process of each person addresses their own feedback won’t work without someone else quality checking it. This is also why we do code reviews everywhere in industry, a person cannot quality check their own work.

D3-3) [task] Look back over the prior feedback on D2 also and the tasks there, everything in green. Add the relevant ones not covered above, if you’re not sure, ask me on Discord in your team channel.

D3-4) [task] For D4 sprint retrospective/review have discussion and notes in the document on the issues/causes raised in the grading feedback, and conclusions must show up in the D4 sprint review

**Comment by KledisZ** [comment]
Assigned architecture design and sprint review issue to Abhilash

**Comment by KledisZ** [comment]
Adressed sequence diagram feedback

**Comment by KledisZ** [comment]
Addressed most of the feedback in Use case descriptions
