### ISSUE TITLE
Software 

### ISSUE THREAD

**Issue by sowthewind-reapthewhirlwind** [COS420-Fall23/Team-G#9]
The implementation should have been started. 

If there is no code/HTML/scripts in Github, this part will be graded as 0.

Setting up the build environments and the necessary dependencies.  

You do not need to have any significant progress on developing your application. Focus on setting up the build environment.You can use create-react-app or otherwise create your project structure.

Your README file should detail the installation and build process for your application. Make sure it works on each person’s machine.

Submit screenshot(s) or a single video showing the app running on each person’s machine 

If there is nothing, deduct -5 points.

**Comment by sowthewind-reapthewhirlwind** [comment]
On my machine
![image](https://github.com/COS420-Fall23/Team-G/assets/39146583/e1a48b00-3b1e-467f-b7e6-b2b0a308e9df)

**Comment by KledisZ** [comment]
<img width="1439" alt="Screenshot 2023-10-08 at 2 17 10 PM" src="https://github.com/COS420-Fall23/Team-G/assets/92754603/c2079f5d-7ed5-4c60-ad30-2e0b9a51f1b0">

**Comment by Dymonkeys** [comment]
![image](https://github.com/COS420-Fall23/Team-G/assets/17692183/ff027eac-3acc-4f81-9dcd-d11ac48a2e4f)

**Comment by knoxbrown** [comment]
<img width="1615" alt="Screen Shot 2023-10-12 at 12 29 43 PM" src="https://github.com/COS420-Fall23/Team-G/assets/137446028/150ecc40-260b-418d-b597-6edd6f77c970">

**Comment by Quinn-Knowles** [comment]
![bearpool screenshot 1](https://github.com/COS420-Fall23/Team-G/assets/143540115/ee7cc5f6-9902-4110-98dc-322e043e2c0d)

**Comment by JohnKearneyyy** [comment]
<img width="1440" alt="Screenshot 2023-10-17 at 6 28 05 PM" src="https://github.com/COS420-Fall23/Team-G/assets/143441853/f40cfe2a-6859-4e62-bb4b-9920a56db42c">

**Comment by TiffanyTHa** [comment]
![Screenshot (14)](https://github.com/COS420-Fall23/Team-G/assets/146392222/e1123dcf-ebec-48aa-8d7f-2744836b3547)
