### ISSUE TITLE
Continous integration

### ISSUE THREAD

**Issue by KledisZ** [COS420-Fall23/Team-G#90]
Setup Continuous Integration for your team’s Github repo using Github Actions or CircleCI.

Here[ relevant](https://github.com/skills/hello-github-actions)[ tutorials](https://github.com/IgnusG/jest-report-action)[ for](https://docs.github.com/en/actions/using-workflows/about-workflows) Github Actions

Here is a [repo](https://github.com/2022-autumn-cos-420/TeamC) from last year with CI correctly set up 
The free version of CircleCI should also work for your project’s size

**Comment by sowthewind-reapthewhirlwind** [comment]
Continous integration has been set up but having some build issues to be resolved
